routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login.login');
})->name('login_index');
//Route::post('Home', 'LoginController@index')->name('home');

//Auth::routes();
Route::post('logeo','Auth\LoginController@login')->name('login');
Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('/Home', 'HomeController@index')->name('home');

/* VOLUNTARIOS */
Route::group(['middleware' => ['permission:mod-voluntaios']], function () {
    Route::get('voluntarios', 'VoluntariosController@index')->name('voluntario.index');
    Route::get('voluntario_alta', 'VoluntariosController@create')->name('voluntario.alta');
    Route::post('voluntario_store', 'VoluntariosController@store')->name('voluntario.store');
    Route::post('voluntario_interaccion', 'VoluntariosController@storeInteraccion')->name('interaccion.store');
    Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
    Route::get('voluntario_edit/{idvoluntario}', 'VoluntariosController@edit')->name('voluntario.edit');
    Route::put('voluntario_update/{idvoluntario}/up', 'VoluntariosController@update')->name('voluntario.update');
    Route::delete('voluntario_destroy/{idvoluntario}', 'VoluntariosController@destroy')->name('voluntario.destroy');
    Route::get('voluntario_interacciones_imprimir/{id}' ,'VoluntariosController@imprimirInteracciones')->name('btn_imprimir');
    Route::post('voluntario_ajax_dni' ,'VoluntariosController@ajaxValidarDni')->name('ajax_dni');
    
    Route::resource('llamadas', 'LlamadasController');
    
    Route::resource('fiscales', 'FiscalController');
    Route::get('fiscales_escuela/{id}' ,'FiscalController@show')->name('fiscales.escuela');
    Route::get('fiscales_mesa/{id}' , 'FiscalController@createFiscal')->name('fiscal.altaFiscal');
    Route::post('fiscales_mesaStore' , 'FiscalController@storeMesa')->name('fiscal.storeMesa');
    Route::delete('fiscales_destroy/{idfiscales}', 'FiscalController@destroy')->name('escuela.destroy');

    Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');
    Route::get('fiscal_alta', 'FiscalController@create')->name('fiscal.alta');
    Route::post('fiscal_store', 'FiscalController@store')->name('fiscal.store');

    
});

Route::group(['middleware' => ['permission:mod-dirigentes']], function () {
    Route::resource('dirigentes', 'DirigentesController');
});
Route::group(['middleware' => ['permission:mod-miembros']], function () {
    Route::resource('miembros', 'MiembrosController');
    
});
Route::group(['middleware' => ['permission:mod-roles-permisos']], function () {
    Route::resource('roles-permisos', 'RolesPermisosController');
});
Route::group(['middleware' => ['permission:mod-usuarios']], function () {
    Route::resource('usuarios', 'UsuariosController');
});

Route::get('circuitos', 'CircuitoController@index')->name('circuitos.index');
Route::get('padron', 'PadronController@index')->name('padron.index');
Route::get('padron-ajax', 'PadronController@listAjax')->name('padron.ajax');
Route::get('padron_create', 'PadronController@create')->name('padron.create');
Route::post('padron_store', 'PadronController@store')->name('padron.store');
Route::get('padron_edit/{idpadron}', 'PadronController@edit')->name('padron.edit');
Route::put('padron_update/{idpadron}/up', 'PadronController@update')->name('padron.update');
Route::delete('padron_destroy/{idpadron}', 'PadronController@destroy')->name('padron.destroy');
Route::post('padron_add','CircuitoController@store')->name('padron.store');

//Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');

//Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
/* 
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
| Domain | Method    | URI                                    | Name                   | Action                                                           | Middleware
    |
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
|        | GET|HEAD  | /                                      | login_index            | Closure                                                          | web
    |
|        | GET|HEAD  | Home                                   | home                   | App\Http\Controllers\HomeController@index                        | web
    |
|        |           |                                        |                        |                                                                  | auth
    |
|        | GET|HEAD  | api/user                               |                        | Closure                                                          | api
    |
|        |           |                                        |                        |                                                                  | auth:api
    |
|        | GET|HEAD  | dirigentes                             | dirigentes.index       | App\Http\Controllers\DirigentesController@index                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | dirigentes                             | dirigentes.store       | App\Http\Controllers\DirigentesController@store                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/create                      | dirigentes.create      | App\Http\Controllers\DirigentesController@create                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | PUT|PATCH | dirigentes/{dirigente}                 | dirigentes.update      | App\Http\Controllers\DirigentesController@update                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}                 | dirigentes.show        | App\Http\Controllers\DirigentesController@show                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | DELETE    | dirigentes/{dirigente}                 | dirigentes.destroy     | App\Http\Controllers\DirigentesController@destroy                | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}/edit            | dirigentes.edit        | App\Http\Controllers\DirigentesController@edit                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | logeo                                  | login                  | App\Http\Controllers\Auth\LoginController@login                  | web
    |
|        | POST      | logout                                 | logout                 | App\Http\Controllers\Auth\LoginController@logout                 | web
    |
|        | POST      | miembros                               | miembros.store         | App\Http\Controllers\MiembrosController@store                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros                               | miembros.index         | App\Http\Controllers\MiembrosController@index                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros/create                        | miembros.create        | App\Http\Controllers\MiembrosController@create                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | DELETE    | miembros/{miembro}                     | miembros.destroy       | App\Http\Controllers\MiembrosController@destroy                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | PUT|PATCH | miembros/{miembro}                     | miembros.update        | App\Http\Controllers\MiembrosController@update                   | web
    |

resources/views/fiscales/create.blade.php
@extends('layout')

@section('title', 'Alta fiscal general')

@section('seccionSaludo')
<h1>Asignar Fiscal General</h1>
@endsection

@section('contenido')

    <div class="col-md-12">
        <div class="row">
            <a href="{{route('fiscales.index')}}" class="btn btn-dark float-left" style="margin-bottom: 3%;">Volver</a>
        </div>
    {{--         <div class="text-center">
            <h3 class="title">Nuevo Fiscal General</h3>
        </div> --}}
        <form id="fiscal_store" action="{{ route('fiscal.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            
           
            
            <div class="row">

                

                <div class="col-lg-6 col-sm-4">
                   <div class="form-group">
                     <label>Escuela:</label>
                     {{-- <input type="hidden" value="{{$escuelas}}" id="repoEscuela"> --}}
                     <select class="form-control"  name="escuela" id="escuelas">
                        <option></option>
                          @foreach($escuelas as $escuela)
                             <option value="{{$escuela->idescuela}}">{{$escuela->circuito_escuela .' - '. $escuela->nombre_escuela}}</option>                        
                          @endforeach
                     </select>
                  </div>
                     <span class="badge badge-danger">{{ $errors->first('escuela')}}</span>
                </div>

                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Dirigente:</label>
                    {{-- <input type="hidden" value="{{$dirigentes}}" id="repoDirigentes"> --}}
                    <select class="form-control"  name="dirigente" id="dirigentes">
                        <option></option>
                        @foreach($dirigentes as $dirigente)
                            <option value="{{$dirigente->id}}">{{$dirigente->nombre .',  ' .$dirigente->apellido}}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('dirigente')}}</span>
                </div>
            </div>


                           <div>
                <button type="submit" class="btn btn-info d-block" style="width:100%">Guardar</button>
            </div>
        </form>
    </div>

@endsection

resources/views/fiscales/createMesa.blade.php
@extends('layout')

@section('title', 'Alta Fiscales')

@section('seccionSaludo')
<h1>Nuevo Fiscal</h1>
<h2> {{$escuelaactual->nombre_escuela}} </h2>
@endsection

@section('contenido')

    <div class="col-md-12">
        <div class="row">
            <a href="{{route('fiscales.index')}}" class="btn btn-dark float-left" style="margin-bottom: 3%;">Volver</a>
        </div>
    {{--         <div class="text-center">
            <h3 class="title">Nuevo Fiscal</h3>
            
        </div> --}}
        <form id="fiscalMesa_store" action="{{ route('fiscal.storeMesa') }}" method="POST" enctype="multipart/form-data">
            @csrf
            
            <div class="row">
            <div class="form-group">
            <input type="hidden" name="escuela" value="{{$escuelaactual->idescuela}}" id="escuela">
            </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Voluntario:</label>
                    {{-- <input type="hidden" value="{{$voluntarios}}" id="repoVoluntarios"> --}}
                    <select class="form-control"  name="voluntario" id="voluntarios">
                        <option></option>
                        @foreach($voluntarios as $voluntario)
                            <option value="{{$voluntario->idvoluntario}}">{{ $voluntario->nombre .',  '.$voluntario->apellido . 'CTO: '. $voluntario->cto_nombre }}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('voluntario')}}</span>
                </div>
                

                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Mesas:</label>
                    <input type="hidden" value="{{$mesas}}" id="repoMesas">
                    <select class="form-control"  name="mesas" id="mesas">
                        <option></option>
                        @foreach($mesas as $mesa)
                            <option value="{{$mesa->idmesa}}">{{$mesa->escuela_mesa.' - '. $mesa->numero_mesa  }}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('mesa')}}</span>
                </div>

                </div>


                           <div>
                <button type="submit" class="btn btn-info d-block" style="width:100%">Guardar</button>
            </div>
        </form>
    </div>

@endsection

resources/views/fiscales/edit.blade.php
@extends('layout')

@section('title', 'Edicion Voluntarios')

@section('seccionSaludo')
<h1>Editar Voluntario</h1>
@endsection

@section('contenido')

    <div class="col-md-12">
        <div class="row">
            <a href="{{route('voluntario.index')}}" class="btn btn-dark float-left" style="margin-bottom: 3%;">Volver</a>
        </div>
{{--         <div class="text-center">
            <h3 class="title">Editar Voluntario</h3>
        </div> --}}
        <form id="voluntario_update" action="{{ route('voluntario.update',$v->idvoluntario) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Nombre:</label>
                    <input type="text" class="form-control" name="nombre" 
                    value="{{$v->nombre}}">
                    </div>
                    
                    <span class="badge badge-danger">{{ $errors->first('nombre')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Apellido:</label>
                    <input type="text" class="form-control" name="apellido" 
                    value="{{$v->apellido}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('apellido')}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>DNI:</label>
                    <input type="number" class="form-control" min="1" step="1" name="dni" 
                    value="{{$v->dni}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('dni')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Coreo:</label>
                    <input type="email" class="form-control" name="email" 
                    value="{{$v->email}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('email')}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Celular:</label>
                    <input type="number" class="form-control" min="1" step="1" name="celular" 
                    value="{{$v->celular}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('nombre')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Telefono:</label>
                    <input type="number" class="form-control" name="telefono" 
                    value="{{$v->telefono}}">
                    </div>
                    
                </div>
            </div>
            <div class="row">

                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Departamentos:</label>
                    <select class="form-control"  name="departamento" id="departamentos">
                        @foreach($departamentos as $depto)
                            <option value="{{$depto->iddepartamento}}"
                                    @if ($depto->iddepartamento == $dpto->iddepartamento)
                                                    {{"selected"}}
                                    @endif>{{$depto->departamento_nombre}}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('departamento')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Localidades:</label>
                    <input type="hidden" value="{{$localidades}}" id="repoLocalidades">
                    <select class="form-control"  name="localidad" id="localidades">
                        @foreach($localidades as $localidad)
                            <option value="{{$localidad->idlocalidad}}"
                                    @if ($localidad->idlocalidad == $local->idlocalidad)
                                                    {{"selected"}}
                                    @endif>{{$localidad->localidad_nombre}}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('localidad')}}</span>
                </div>
                
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Fecha de Nacimiento:</label>
                    <input type="date" class="form-control" name="fecha_nacimiento"
                    value="{{$v->fecha_nacimiento}}"
                    min="{{$Amin}}-01-01" max="{{$Amax}}-12-31">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('fecha_nacimiento')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group">
                    <label>Circuitos:</label>
                    <input type="hidden" value="{{$circuitos}}" id="repoCircuitos">
                    <select class="form-control"  name="circuitos" id="circuitos">
                        <option></option>
                        @foreach($circuitos as $circuito)
                            <option value="{{$circuito->idcircuito}}"
                                    @if ($circuito->idcircuito == $v->circuito_idcircuito)
                                                    {{"selected"}}
                                    @endif>{{$circuito->circuito_nombre}}</option>                        
                        @endforeach
                    </select>
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('circuitos')}}</span>
                </div>
            </div>
                <h5 for="sel1">Direccion:</h5>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Calle:</label>
                    <input type="text" class="form-control" name="calle" 
                    value="{{$dir->calle}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('calle')}}</span>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Número:</label>
                    <input type="number" class="form-control" name="numero" 
                    value="{{$dir->numero}}">
                    </div>
                    <span class="badge badge-danger">{{ $errors->first('numero')}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Pisp:</label>
                    <input type="text" class="form-control" name="piso" value="{{$dir->piso}}">
                    </div>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Departamento:</label>
                    <input type="text" class="form-control" name="dpto" 
                            value="{{$dir->dpto}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Manzana:</label>
                    <input type="text" class="form-control" name="manzana" 
                            value="{{$dir->manzana}}">
                    </div>
                </div>
                <div class="col-lg-6 col-sm-4">
                    <div class="form-group has-default">
                    <label>Casa:</label>
                    <input type="text" class="form-control" name="casa" 
                            value="{{$dir->casa}}">
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                <label>Origen:</label>
                <select class="form-control"  name="origen" id="origen">
                    <option></option>
                    <option value="1" 
                        @if ('IPEC' == $v->origen)
                          {{"selected"}}
                        @endif>IPEC</option>
                    <option value="2" 
                        @if ('Territorio' == $v->origen)
                          {{"selected"}}
                        @endif>Territorio</option>
                    <option value="3" 
                        @if ('Redes Sociales' == $v->origen)
                          {{"selected"}}
                        @endif>Redes Sociales</option>
                    <option value="4" 
                        @if ('Sumatoria de voluntarios' == $v->origen)
                          {{"selected"}}
                        @endif>Sumatoria de voluntarios</option>
                    <option value="5" 
                        @if ('Pro vida' == $v->origen)
                          {{"selected"}}
                        @endif>Pro vida</option>
                    <option value="6" 
                        @if ('Emprended' == $v->origen)
                          {{"selected"}}
                        @endif>Emprendedores</option>
                </select>
                </div>
                <span class="badge badge-danger">{{ $errors->first('localidad')}}</span>
            </div>
            <div class="row d-flex justify-content-center" style="margin-bottom: 4%;">
                <div class="d-flex justify-content-around" >
                    <img class="img-raised rounded img-fluid" id="Foto"src="{{$v->foto}}" alt="Foto" style="width: 35%;height: 35vh;">
                    <div class="">
                        <h5>Actualizar Foto</h5>
                        <input type="file" class="form-control" id="fotoVoluntario" name="file">
                        <span class="badge badge-danger">{{ $errors->first('file')}}</span>
                    </div>
                </div>                
            </div>
            <div>
                <button type="submit" class="btn btn-info d-block" style="width:100%">Actualizar</button>
            </div>
        </form>
    </div>

@endsection

@section('script')
<script>
$(document).ready(function(){
    var localidades = JSON.parse( $('#repoLocalidades').val() );
    var circuitos = JSON.parse($('#repoCircuitos').val());
    $('#departamentos').change(function(e){
        var iddpto = $(this).val();
        $('#localidades').html('');
        $('#localidades').append('<option></option>');
        localidades.forEach((elem)=>{
            if(iddpto == elem.departamento_iddepartamento){
                $('#localidades').append('<option value="'+elem.idlocalidad+'">'+elem.localidad_nombre+'</option>');
            }
        });
        $('#circuitos').html('');
    });
    $('#localidades').change(function(e){
        var idlocalidad = $(this).val();
        $('#circuitos').html('');
        $('#circuitos').append('<option></option>');
        circuitos.forEach((elem)=>{
            if(idlocalidad == elem.localidad_idlocalidad){
                $('#circuitos').append('<option value="'+elem.idcircuito+'">'+elem.circuito_nombre+'</option>');
            }
        });
    });
    $("#fotoVoluntario").on("change", function(e) {
        var TmpPath = URL.createObjectURL(e.target.files[0]);
        // Mostramos la ruta temporal
        $('#Foto').attr('src', TmpPath);
    });
});
</script>
@endsection

resources/views/fiscales/index.blade.php
@extends('layout')
@php

    use App\Escuela;
    use App\CircuitoFiscal;
    use App\User;

@endphp
@section('title', 'Escuelas')

@section('seccionSaludo')
<h1>Listado de Escuelas</h1>
{{-- <h3 class="title text-center">---</h3> --}}
@endsection

@section('contenido')
    <div class="col-md-12">

    <div class="row">
        {{-- @can('fiscal-alta') --}}
                <a href="{{route('fiscal.alta')}}"; class="btn btn-success" style="margin-left: 89%;">Designar fiscal general</a>
                {{--    @endcan --}}
        </div>

        <div class="table-responsive" id="seccionTabla">
            <table class="table table-striped table-dark table-sm" id="tableVoluntarios" class="display compact" style="width:100%">
                <thead class="thead-dark">
                <tr>
                    <th>Circuito</th>
                    <th>Escuela</th>
                    <th>Fiscal General</th>
                    <th>Celular</th>
                    <th>Estado</th>
                    
                    <th></th>
                    <th></th>
                    
                </tr>
                </thead>
                <tbody>
                    @foreach($escuelas as $esc)  
                       
                       
                                
                        <tr>
                            <td> {{ $esc->circuito}}  </td>
                            @if (  $esc->estado == "completo")
                                 <td style="background-color:green">
                                    {{ $esc->nombre_escuela}}
                                </td>
                            @else
                                  <td >
                                    {{ $esc->nombre_escuela}}
                                </td>
                                @endif
                            <td>{{ $esc->nombre_fiscal . $esc->apellido_fiscal}}</td>
                            <td>{{ $esc->celular}}</td>
                            <td>{{ $esc->estado}}</td>
                            
                           
                            <td>
                                @can('voluntario-detalle')                                    
                                <a href="{{route('fiscales.show',$esc->idescuela)}}" class="showEscuela" id="show_{{ $esc->idescuela}}"><i class="far fa-eye fa-2x"></i></a>
                                                         
                                @endcan                          
                            </td>
                            <td>
                              <!--   @can('voluntario-edicion')                                    
                                <a href="{{route('voluntario.edit',$esc->idescuela)}}" class="editVoluntario" id="edit_{{ $esc->idescuela}}"><i class="far fa-edit fa-2x"></i></a>
                                @endcan -->
                         </tr>
                         
                    @endforeach
                </tbody>
            </table>

        </div>

        
    </div>

@endsection

@section('script')
<script>
/* EMERGENTES */
function mjsAlert(id){
    $(id).show('slow');
    setTimeout(function() {
    $('.message').hide('slow');
    }, 3500);
}// FIN EMERGENTES //
</script>
@endsection