routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login.login');
})->name('login_index');
//Route::post('Home', 'LoginController@index')->name('home');

//Auth::routes();
Route::post('logeo','Auth\LoginController@login')->name('login');
Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('/Home', 'HomeController@index')->name('home');

/* VOLUNTARIOS */
Route::group(['middleware' => ['permission:mod-voluntaios']], function () {
    Route::get('voluntarios', 'VoluntariosController@index')->name('voluntario.index');
    Route::get('voluntario_alta', 'VoluntariosController@create')->name('voluntario.alta');
    Route::post('voluntario_store', 'VoluntariosController@store')->name('voluntario.store');
    Route::post('voluntario_interaccion', 'VoluntariosController@storeInteraccion')->name('interaccion.store');
    Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
    Route::get('voluntario_edit/{idvoluntario}', 'VoluntariosController@edit')->name('voluntario.edit');
    Route::put('voluntario_update/{idvoluntario}/up', 'VoluntariosController@update')->name('voluntario.update');
    Route::delete('voluntario_destroy/{idvoluntario}', 'VoluntariosController@destroy')->name('voluntario.destroy');
    Route::get('voluntario_interacciones_imprimir/{id}' ,'VoluntariosController@imprimirInteracciones')->name('btn_imprimir');
    Route::post('voluntario_ajax_dni' ,'VoluntariosController@ajaxValidarDni')->name('ajax_dni');
    
    Route::resource('llamadas', 'LlamadasController');
    
    Route::resource('fiscales', 'FiscalController');
    Route::get('fiscales_escuela/{id}' ,'FiscalController@show')->name('fiscales.escuela');
    Route::get('fiscales_mesa/{id}' , 'FiscalController@createFiscal')->name('fiscal.altaFiscal');
    Route::post('fiscales_mesaStore' , 'FiscalController@storeMesa')->name('fiscal.storeMesa');
    Route::delete('fiscales_destroy/{idfiscales}', 'FiscalController@destroy')->name('escuela.destroy');

    Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');
    Route::get('fiscal_alta', 'FiscalController@create')->name('fiscal.alta');
    Route::post('fiscal_store', 'FiscalController@store')->name('fiscal.store');

    
});

Route::group(['middleware' => ['permission:mod-dirigentes']], function () {
    Route::resource('dirigentes', 'DirigentesController');
});
Route::group(['middleware' => ['permission:mod-miembros']], function () {
    Route::resource('miembros', 'MiembrosController');
    
});
Route::group(['middleware' => ['permission:mod-roles-permisos']], function () {
    Route::resource('roles-permisos', 'RolesPermisosController');
});
Route::group(['middleware' => ['permission:mod-usuarios']], function () {
    Route::resource('usuarios', 'UsuariosController');
});

Route::get('circuitos', 'CircuitoController@index')->name('circuitos.index');
Route::get('padron', 'PadronController@index')->name('padron.index');
Route::get('padron-ajax', 'PadronController@listAjax')->name('padron.ajax');
Route::get('padron_create', 'PadronController@create')->name('padron.create');
Route::post('padron_store', 'PadronController@store')->name('padron.store');
Route::get('padron_edit/{idpadron}', 'PadronController@edit')->name('padron.edit');
Route::put('padron_update/{idpadron}/up', 'PadronController@update')->name('padron.update');
Route::delete('padron_destroy/{idpadron}', 'PadronController@destroy')->name('padron.destroy');
Route::post('padron_add','CircuitoController@store')->name('padron.store');

//Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');

//Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
/* 
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
| Domain | Method    | URI                                    | Name                   | Action                                                           | Middleware
    |
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
|        | GET|HEAD  | /                                      | login_index            | Closure                                                          | web
    |
|        | GET|HEAD  | Home                                   | home                   | App\Http\Controllers\HomeController@index                        | web
    |
|        |           |                                        |                        |                                                                  | auth
    |
|        | GET|HEAD  | api/user                               |                        | Closure                                                          | api
    |
|        |           |                                        |                        |                                                                  | auth:api
    |
|        | GET|HEAD  | dirigentes                             | dirigentes.index       | App\Http\Controllers\DirigentesController@index                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | dirigentes                             | dirigentes.store       | App\Http\Controllers\DirigentesController@store                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/create                      | dirigentes.create      | App\Http\Controllers\DirigentesController@create                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | PUT|PATCH | dirigentes/{dirigente}                 | dirigentes.update      | App\Http\Controllers\DirigentesController@update                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}                 | dirigentes.show        | App\Http\Controllers\DirigentesController@show                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | DELETE    | dirigentes/{dirigente}                 | dirigentes.destroy     | App\Http\Controllers\DirigentesController@destroy                | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}/edit            | dirigentes.edit        | App\Http\Controllers\DirigentesController@edit                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | logeo                                  | login                  | App\Http\Controllers\Auth\LoginController@login                  | web
    |
|        | POST      | logout                                 | logout                 | App\Http\Controllers\Auth\LoginController@logout                 | web
    |
|        | POST      | miembros                               | miembros.store         | App\Http\Controllers\MiembrosController@store                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros                               | miembros.index         | App\Http\Controllers\MiembrosController@index                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros/create                        | miembros.create        | App\Http\Controllers\MiembrosController@create                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | DELETE    | miembros/{miembro}                     | miembros.destroy       | App\Http\Controllers\MiembrosController@destroy                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | PUT|PATCH | miembros/{miembro}                     | miembros.update        | App\Http\Controllers\MiembrosController@update                   | web
    |

resources/views/miembros/index.blade.php
@extends('layout')

@section('title', 'Miembros')

@section('seccionSaludo')
<h1>Listado de Coordinadores</h1>
{{-- <h3 class="title text-center">---</h3> --}}
@endsection

@section('contenido')
    <div class="col-md-12">
        <div class="row">
            @can('coordinador-alta')                
            <a href="{{route('miembros.create')}}"; class="btn btn-success" style="margin-left: 89%;">Nuevo Coordinador</a>
            @endcan
        </div>
        <div class="table-responsive" id="seccionTabla">
            <table class="table table-striped table-dark table-sm" id="tableMiembros">
                <thead class="thead-dark">
                <tr>
                    <th>Nombre y Apellido</th>
                    <th>Celular</th>
                    <th>Email</th>
                    <th>Circuito</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($array_miembros as $miembro)  
                        <tr>
                            <td>{{ $miembro->apellido .','.$miembro->nombre}}</td>
                            <td>{{ $miembro->celular}}</td>
                            <td>{{ $miembro->email}}</td>
                            @if (count($miembro->circuitos)>0)                                
                                <td>{{ $miembro->circuitos()->wherePivot('es_responsable',2)->get()[0]->circuito_nombre}}</td>
                            @else
                            <td>{{ '---' }}</td>                                
                            @endif
                            <td>
                                @can('coordinador-detalle')                
                                <a href="javascript:;" class="showMiembro" id="show_{{ $miembro->id}}"><i class="far fa-eye fa-2x"></i></a>                            
                                @endcan
                            </td>
                            <td>
                                @can('coordinador-edicion')                
                                <a href="{{route('miembros.edit',$miembro->id)}}" class="editmiembro" id="edit_{{ $miembro->id}}"><i class="far fa-edit fa-2x"></i></a>
                                @endcan
                            </td>
                            <td>
                                @can('coordinador-eliminar')                
                                <a href="javascript:;"
                                    onclick="eliminarMiembro({{ $miembro->id}});" ><i class="fas fa-times fa-2x"></i></a>
                                <form id="delete-form_{{ $miembro->id}}" action="{{ route('miembros.destroy',$miembro->id) }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form> 
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

        <div class="text-center" id="seccionDatos" style="display:none;">
            <h3 id="nombreCoordinador"></h3>
            <div class="row">
                @include('view_repositorios.card_info', array('cardHeader'=>'COORDINADOR'))                
            </div>
            <div class="title">
                <h3><small>RESPONSABILIDADES</small></h3>
            </div>
            <div class="row">

                <div class="col-lg-12 col-md-12">
                  <div class="row">
                    <div class="col-md-3">
                      <ul class="nav nav-pills nav-pills-primary nav-pills-icons flex-column" role="tablist">
                        <!--
                                            color-classes: "nav-pills-primary", "nav-pills-info", "nav-pills-success", "nav-pills-warning","nav-pills-danger"
                                        -->
                        <li class="nav-item">
                          <a class="nav-link active" href="#sec-circuito" role="tab" data-toggle="tab">
                            <i class="fas fa-road fas-x2"></i>
                            Circuitos
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#sec-localidades" role="tab" data-toggle="tab">
                            <i class="fas fa-map-marked-alt fas-x2"></i>
                            Localidades
                          </a>
                        </li>
                      </ul>
                    </div>
                    <div class="col-md-8">
                      <div class="tab-content">
                        <div class="tab-pane active" id="sec-circuito">                            
                                {{-- <span class="badge badge-pill badge-info">Info</span>     --}}                        
                        </div>
                        <div class="tab-pane" id="sec-localidades">
                         
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>

            <button class="btn btn-primary btn-sm pull-left" id="volverList">Volver al listado<div class="ripple-container"></div></button>
        </div>
    </div>


@endsection

@section('script')
<script>
$(document).ready(function() {
    setTimeout(function() {
      $('#message').fadeOut('fast');
    }, 3500);

    const TCordinadores = $('#tableMiembros').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'pdfHtml5',
        ],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
        },
        // pageLength : 5,
        lengthMenu: [[10, 20, -1], [10, 20, 'Todos']]
        
    });
    TCordinadores.page.len(20).draw();
});

function eliminarMiembro(idMiembro){
    if(confirm('Esta acción no podrá deshacerse. ¿Continuar?')){

        document.getElementById('delete-form_'+idMiembro).submit();
    }
}
$(document).on('click','.showMiembro',function(){
    let id = $(this).prop('id').split('_')[1];
    let ruta  =  "{{ URL::to('miembros/') }}"+"/"+id;
    $.ajax({
      type: 'GET',
      url: ruta,
      beforeSend: function(){ },
      error: function(jqxhr, textStatus, error){
          console.log(error);
      },
      success: function(respuesta){
        
        if (respuesta.status ) {
            $('#nombreCoordinador').html(respuesta.usuario.apellido+', '+respuesta.usuario.nombre);
            $('#foto').attr( "src" ,respuesta.usuario.foto);
            $('#direccion').html(respuesta.direccion.calle+' '+respuesta.direccion.numero);
            $('#telefono').html(respuesta.usuario.telefono);
            $('#celular').html(respuesta.usuario.celular);
            $('#correo').html(respuesta.usuario.email);
            $('#localidad').html(respuesta.localidad.localidad_nombre);
            $('#departamento').html(respuesta.departamento.departamento_nombre);
            respuesta.respCircuitos.forEach(element => {
                let span = `<span class="badge badge-pill badge-info">${element.circuito_nombre}</span>`;
                $('#sec-circuito').append(span);
            });
            respuesta.respLocalidades.forEach(element => {
                let span = `<span class="badge badge-pill badge-info">${element.localidad_nombre}</span>`;
                $('#sec-localidades').append(span);
            });
            $('#seccionTabla').hide('slow');
            $('#seccionDatos').show('slow');
        }
      },
      dataType: 'json',
      async:true
    });

});

$(document).on('click','#volverList',function(){
    $('#seccionDatos').hide('slow');
    $('#seccionTabla').show('slow');
});
</script>
@endsection