routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login.login');
})->name('login_index');
//Route::post('Home', 'LoginController@index')->name('home');

//Auth::routes();
Route::post('logeo','Auth\LoginController@login')->name('login');
Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('/Home', 'HomeController@index')->name('home');

/* VOLUNTARIOS */
Route::group(['middleware' => ['permission:mod-voluntaios']], function () {
    Route::get('voluntarios', 'VoluntariosController@index')->name('voluntario.index');
    Route::get('voluntario_alta', 'VoluntariosController@create')->name('voluntario.alta');
    Route::post('voluntario_store', 'VoluntariosController@store')->name('voluntario.store');
    Route::post('voluntario_interaccion', 'VoluntariosController@storeInteraccion')->name('interaccion.store');
    Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
    Route::get('voluntario_edit/{idvoluntario}', 'VoluntariosController@edit')->name('voluntario.edit');
    Route::put('voluntario_update/{idvoluntario}/up', 'VoluntariosController@update')->name('voluntario.update');
    Route::delete('voluntario_destroy/{idvoluntario}', 'VoluntariosController@destroy')->name('voluntario.destroy');
    Route::get('voluntario_interacciones_imprimir/{id}' ,'VoluntariosController@imprimirInteracciones')->name('btn_imprimir');
    Route::post('voluntario_ajax_dni' ,'VoluntariosController@ajaxValidarDni')->name('ajax_dni');
    
    Route::resource('llamadas', 'LlamadasController');
    
    Route::resource('fiscales', 'FiscalController');
    Route::get('fiscales_escuela/{id}' ,'FiscalController@show')->name('fiscales.escuela');
    Route::get('fiscales_mesa/{id}' , 'FiscalController@createFiscal')->name('fiscal.altaFiscal');
    Route::post('fiscales_mesaStore' , 'FiscalController@storeMesa')->name('fiscal.storeMesa');
    Route::delete('fiscales_destroy/{idfiscales}', 'FiscalController@destroy')->name('escuela.destroy');

    Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');
    Route::get('fiscal_alta', 'FiscalController@create')->name('fiscal.alta');
    Route::post('fiscal_store', 'FiscalController@store')->name('fiscal.store');

    
});

Route::group(['middleware' => ['permission:mod-dirigentes']], function () {
    Route::resource('dirigentes', 'DirigentesController');
});
Route::group(['middleware' => ['permission:mod-miembros']], function () {
    Route::resource('miembros', 'MiembrosController');
    
});
Route::group(['middleware' => ['permission:mod-roles-permisos']], function () {
    Route::resource('roles-permisos', 'RolesPermisosController');
});
Route::group(['middleware' => ['permission:mod-usuarios']], function () {
    Route::resource('usuarios', 'UsuariosController');
});

Route::get('circuitos', 'CircuitoController@index')->name('circuitos.index');
Route::get('padron', 'PadronController@index')->name('padron.index');
Route::get('padron-ajax', 'PadronController@listAjax')->name('padron.ajax');
Route::get('padron_create', 'PadronController@create')->name('padron.create');
Route::post('padron_store', 'PadronController@store')->name('padron.store');
Route::get('padron_edit/{idpadron}', 'PadronController@edit')->name('padron.edit');
Route::put('padron_update/{idpadron}/up', 'PadronController@update')->name('padron.update');
Route::delete('padron_destroy/{idpadron}', 'PadronController@destroy')->name('padron.destroy');
Route::post('padron_add','CircuitoController@store')->name('padron.store');

//Route::get('fiscales', 'FiscalController@index')->name('fiscales.index');

//Route::get('voluntario_show/{idvoluntario}', 'VoluntariosController@show')->name('voluntario.show');
/* 
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
| Domain | Method    | URI                                    | Name                   | Action                                                           | Middleware
    |
+--------+-----------+----------------------------------------+------------------------+------------------------------------------------------------------+-------------------------------+
|        | GET|HEAD  | /                                      | login_index            | Closure                                                          | web
    |
|        | GET|HEAD  | Home                                   | home                   | App\Http\Controllers\HomeController@index                        | web
    |
|        |           |                                        |                        |                                                                  | auth
    |
|        | GET|HEAD  | api/user                               |                        | Closure                                                          | api
    |
|        |           |                                        |                        |                                                                  | auth:api
    |
|        | GET|HEAD  | dirigentes                             | dirigentes.index       | App\Http\Controllers\DirigentesController@index                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | dirigentes                             | dirigentes.store       | App\Http\Controllers\DirigentesController@store                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/create                      | dirigentes.create      | App\Http\Controllers\DirigentesController@create                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | PUT|PATCH | dirigentes/{dirigente}                 | dirigentes.update      | App\Http\Controllers\DirigentesController@update                 | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}                 | dirigentes.show        | App\Http\Controllers\DirigentesController@show                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | DELETE    | dirigentes/{dirigente}                 | dirigentes.destroy     | App\Http\Controllers\DirigentesController@destroy                | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | GET|HEAD  | dirigentes/{dirigente}/edit            | dirigentes.edit        | App\Http\Controllers\DirigentesController@edit                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-dirigentes 
    |
|        | POST      | logeo                                  | login                  | App\Http\Controllers\Auth\LoginController@login                  | web
    |
|        | POST      | logout                                 | logout                 | App\Http\Controllers\Auth\LoginController@logout                 | web
    |
|        | POST      | miembros                               | miembros.store         | App\Http\Controllers\MiembrosController@store                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros                               | miembros.index         | App\Http\Controllers\MiembrosController@index                    | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | GET|HEAD  | miembros/create                        | miembros.create        | App\Http\Controllers\MiembrosController@create                   | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | DELETE    | miembros/{miembro}                     | miembros.destroy       | App\Http\Controllers\MiembrosController@destroy                  | web
    |
|        |           |                                        |                        |                                                                  | permission:mod-miembros   
    |
|        | PUT|PATCH | miembros/{miembro}                     | miembros.update        | App\Http\Controllers\MiembrosController@update                   | web
    |

app/Http/Controllers/RolesPermisosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesPermisosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
       // dd($roles);
        return view('roles_permisos.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permisos = Permission::all();
        return view('roles_permisos.create',compact('permisos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rol = Role::create(['name' => $request->rol]);
        $permisos = json_decode( $request->permisos );
        if(  count($permisos) > 0){
            $arrP = array();
            foreach ($permisos as $key) {
                array_push($arrP, $key->id);
            }
            //$rol->permissions()->sync($arrP);
            $rol->syncPermissions($arrP);
            //$rol->syncPermissions($arrP);
        }
        return redirect()->route('roles-permisos.index')->with('success','Rol creado Correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permisos = Permission::all();
        $rol = Role::find($id);
       // dd($permisos);
        return view('roles_permisos.edit',compact('permisos','rol'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rol = Role::find($id);
        $permisos = json_decode( $request->permisos );
        if(  count($permisos) > 0){
            $arrP = array();
            foreach ($permisos as $key) {
                array_push($arrP, $key->id);
            }
            //$rol->permissions()->sync($arrP);
            $rol->syncPermissions($arrP);
            //$rol->syncPermissions($arrP);
        }
        return redirect()->route('roles-permisos.index')->with('success','Permisos Asignados Correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $rol = Role::find($id);
        $rol->delete();
        return redirect()->route('roles-permisos.index')->with('success','Rol eliminado Correctamente');
    }
}

resources/views/roles_permisos/create.blade.php
@extends('layout')

@section('title', 'Edicion roles-permisoss')

@section('seccionSaludo')
<h1>Crear Rol - Permisos</h1>
@endsection

@section('contenido')

    <div class="col-md-12">
        <div class="row">
            <a href="{{route('roles-permisos.index')}}" class="btn btn-dark float-left" style="margin-bottom: 3%;">Volver</a>
        </div>

        <form id="roles_permisos_store" action="{{ route('roles-permisos.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="form-group has-default">
                        <label>Nombre del Rol:</label>
                        <input type="text" class="form-control" name="rol" placeholder="nombre-del-rol" 
                        value="{{old('rol')}}">
                        </div>
                        
                        <span class="badge badge-danger">{{ $errors->first('rol')}}</span>
                </div>
            </div>

            <div class="col-12">
                <input type="hidden" id="permisos" name="permisos">
                <div class="form-group">
                <label>Permisos:</label>
                <select class="form-control single" name="select_permisos" id="select_permisos">
                    <option></option>
                    @foreach($permisos as $permiso)
                        <option value="{{$permiso->id}}">{{$permiso->name." - ".$permiso->guard_name}}</option>  
                    @endforeach
                </select>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                <label>Permisos seleccionados:</label>
                <input class="inputTag form-control" type="text" value="" data-role="tagsinput sometext" >
            </div>

            <div>
                <button id="guardarRol" class="btn btn-info d-block" style="width:100%">Guardar</button>
            </div>
        </form>
    </div>

@endsection

@section('script')
<script>
    $('.single').select2();
    $('.select2-container').on('click',function (a) {
      $("input[type=search]").attr("placeholder", "Buscar...");
    });

$(document).on('click','#guardarRol',function(){
    event.preventDefault();
    var tags = $('.inputTag').tagsinput('items');
        $('#permisos').val(JSON.stringify(tags));

    console.log(JSON.stringify(tags));
   document.getElementById('roles_permisos_store').submit();

});
$(document).ready(function(){
    $('.inputTag').tagsinput({// CONFIGURACION
        allowDuplicates: false,
        tagClass: 'badge badge-primary',
        itemValue: 'id',
        itemText: 'text'
    });
});
$('#select_permisos').on('change',function(){ //CONTROL PARA AGREGAR TAGS
    if($(this).val()!=""){

        let obj = {
            id:$(this).val(),
            text:$('#select_permisos option:selected').html()
        };
        $('.inputTag').tagsinput('add', obj);

    } 
});

function addTags(obj){
 $('.inputTag').tagsinput('add', obj);
}

</script>
@endsection

resources/views/roles_permisos/edit.blade.php
@extends('layout')

@section('title', 'Edicion roles-permisoss')

@section('seccionSaludo')
<h1>Editar Permisos</h1>
@endsection

@section('contenido')

    <div class="col-md-12">
        <div class="row">
            <a href="{{route('roles-permisos.index')}}" class="btn btn-dark float-left" style="margin-bottom: 3%;">Volver</a>
        </div>

        <form id="roles_permisos_update" action="{{ route('roles-permisos.update',$rol->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-12">
                    <div class="form-group text-center">
                    <h1>{{$rol->name}}</h1>
                    </div>
                </div>
            </div>

            <div class="col-12">
                <input type="hidden" id="permisos" name="permisos">
                <div class="form-group">
                <label>Permisos:</label>
                <select class="form-control single" name="select_permisos" id="select_permisos">
                    <option></option>
                    @foreach($permisos as $permiso)
                        <option value="{{$permiso->id}}">{{$permiso->name." - ".$permiso->guard_name}}</option>  
                    @endforeach
                </select>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                <label>Permisos seleccionados:</label>
                <input class="inputTag form-control" type="text" value="" data-role="tagsinput sometext" >
            </div>

            <div>
                <button id="guardarRol" class="btn btn-info d-block" style="width:100%">Actualizar</button>
            </div>
        </form>
    </div>

@endsection

@section('script')
<script>
    $('.single').select2();
    $('.select2-container').on('click',function (a) {
      $("input[type=search]").attr("placeholder", "Buscar...");
    });
$(document).on('click','#guardarRol',function(){
    event.preventDefault();
    var tags = $('.inputTag').tagsinput('items');
        $('#permisos').val(JSON.stringify(tags));

    console.log(JSON.stringify(tags));
   document.getElementById('roles_permisos_update').submit();

});
$(document).ready(function(){
    $('.inputTag').tagsinput({// CONFIGURACION
        allowDuplicates: false,
        tagClass: 'badge badge-primary',
        itemValue: 'id',
        itemText: 'text'
    });
});
$('#select_permisos').on('change',function(){ //CONTROL PARA AGREGAR TAGS
    if($(this).val()!=""){

        let obj = {
            id:$(this).val(),
            text:$('#select_permisos option:selected').html()
        };
        $('.inputTag').tagsinput('add', obj);

    } 
});
$(document).ready(function(){
    @foreach($rol->permissions as $perm)
        addTags({id:'{{$perm->id}}',text:'{{$perm->name}}'});
    @endforeach
});
function addTags(obj){
 $('.inputTag').tagsinput('add', obj);
}

</script>
@endsection

resources/views/roles_permisos/index.blade.php
@extends('layout')

@section('title', 'Roles')

@section('seccionSaludo')
<h1>Listado de Roles y Permisos</h1>
@endsection

@section('contenido')

    <div class="col-md-12">

        <div class="row">
            @can('rol-alta')                
            <a href="{{route('roles-permisos.create')}}"; class="btn btn-success" style="margin-left: 89%;">Nuevo Rol - Permisos</a>
            @endcan
        </div>
        <div class="table-responsive" id="seccionTabla">
            <table class="table table-striped table-dark table-sm" id="tableRolPermisos">
                <thead class="thead-dark">
                <tr>
                    <th>Rol</th>
                    <th>CRUD</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($roles as $rol)  
                        <tr>
                            @if ($rol->id == 2)
                            <td>Coordinador</td>                                
                            @else                                
                            <td>{{ $rol->name}}</td>
                            @endif
                            <td>
                                @can('rol-edicion')                
                                <a href="{{route('roles-permisos.edit',$rol->id)}}" class="editrol" id="edit_{{ $rol->id}}"><i class="far fa-edit fa-2x"></i></a>
                                @endcan
                                @can('rol-eliminar')                
                                <a href="javascript:;"
                                    onclick="eliminarrol({{ $rol->id}});"><i class="fas fa-times fa-2x"></i></a>
                                <form id="delete-form_{{ $rol->id}}" action="{{ route('roles-permisos.destroy',$rol->id) }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>                                
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

    </div>

@endsection

@section('script')
<script>

$(document).ready(function() {
    setTimeout(function() {
      $('#message').fadeOut('fast');
    }, 3500);

    const TRolPermisos = $('#tableRolPermisos').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
        },
        // pageLength : 5,
        lengthMenu: [[10, 20, -1], [10, 20, 'Todos']]
        
    });
    TRolPermisos.len(20).draw();
    
    tableInteracciones = $('#tablaInteracciones').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
        },
        // pageLength : 5,
        lengthMenu: [[5,10, 20, -1], [5,10, 20, 'Todos']],
        
    });
});
function eliminarrol(idrol){
    if(confirm('Esta acción no podrá deshacerse. ¿Continuar?')){

        document.getElementById('delete-form_'+idrol).submit();
    }
}
</script>
@endsection